### ISSUE TITLE
Feature Request: Be able to choose your game version

### ISSUE THREAD

**Issue by BruhDingusLBozo** [Lauriethefish/ModsBeforeFriday#26]
Instead of being forced to use the latest moddable version, we should be able to choose our version of choice like 1.28 and get the mods for that version.

**Comment by Lauriethefish** [comment]
Initial note: MBF does not force you to use the latest moddable version, it in fact allows you to select any version supported by MBF, which right now is versions 1.37 or 1.35.

Supporting beat saber version 1.28 requires a different mod loader (quest loader) to the one mbf installs (scotland2) and mods for 1.28 get installed into an entirely separate mods folder because of this. For this reason, supporting 1.28 has always been an explicit non-goal for MBF. 

1.28 is quite unstable frankly and it will be deprecated soon once the final few mods are updated to 1.37.

Anyway that's why I'm closing this as not planned.
