### ISSUE TITLE
MBF ZIP library has no data descriptor support so cannot import songs from Beat Saver

### ISSUE THREAD

**Issue by marketingmagi** [Lauriethefish/ModsBeforeFriday#36]
Getting this error when attempting to import songs on Quest 2: 'Failed to fill whole buffer'

![Screenshot 2024-09-04 164457](https://github.com/user-attachments/assets/0ca48217-abd4-4d22-bdf4-98c5fcff4aec)

**Comment by Lauriethefish** [comment]
It appears as though the Beat Saver website generates ZIP files that use a data descriptor (internal format detail) to specify the length of the `Info.dat` file. This is causing a failure when MBF attempts to extract this file as it cannot correctly determine the file length.

This will be fixed in a future update. NB: You can work around this issue by extracting the song file in windows explorer or with 7zip, then recompressing it back into a ZIP file.

**Comment by Lauriethefish** [comment]
Issue is fixed but not yet deployed onto the main site.
You can view the nightly version of the fix [here](https://lauriethefish.github.io/mbf-nightly/) on the nightly site.

**Comment by Lauriethefish** [comment]
Fix is now deployed to the main site.
