### ISSUE TITLE
Device in use

### ISSUE THREAD

**Issue by frankqgu** [Lauriethefish/ModsBeforeFriday#9]
![image](https://github.com/Lauriethefish/ModsBeforeFriday/assets/130730924/1d650fd1-24cb-48e2-b6d9-c9dc27322a60)
Constantly getting this image. Not sure what other app is trying to access my quest as I've already trashed and deleted sidequest and similars
Ubuntu 22.04, initially installed sidequest but uninstalled it as while trying to detect device on modsbeforefriday it prompted that the device was in use somewhere else, Then restarted both device and pc multiple times and to no avail
Maybe it's because I've already remembered this device on the headset or just a linux specific problem?

**Comment by WombleWoo7547** [comment]
Try:
```bash
sudo killall adb
```
if that doesn't work...
```bash
htop
```
(install if needed)
and find apps that are simmilar to kill them.
Otherwise use a friend or family member's computer to do this.

**Comment by fullStackRacc** [comment]
Also, I've been having this a lot. I found out that (at least some of the time) that it's asking you to connect the quest to the computer inside the quest. Like if you go to notifications there's one to ask it to connect to your computer. 

Been working great for me since i realized that

**Comment by Lauriethefish** [comment]
Heya, there seems to be a bug here where the "device in use" prompts shows up if any issue occurs while connecting, even if it isn't related to the device being claimed already. I've fixed this so that MBF should now properly report any other errors occurring while connecting. 

Please let me know if you get a new error message and provide it here!

**Comment by Lauriethefish** [comment]
Closing since no further comments provided
